/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "projector_client.h"
#include "WindowDLG.h"

#include "cmsis_os.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x03)
#define ID_BUTTON_0 (GUI_ID_USER + 0x04)
#define ID_BUTTON_1 (GUI_ID_USER + 0x06)
#define ID_BUTTON_2 (GUI_ID_USER + 0x07)
#define ID_TEXT_0 (GUI_ID_USER + 0x08)
#define ID_TEXT_1 (GUI_ID_USER + 0x09)
#define ID_TEXT_2 (GUI_ID_USER + 0x0A)
#define ID_TEXT_3 (GUI_ID_USER + 0x0B)
#define ID_TEXT_4 (GUI_ID_USER + 0x0C)
#define ID_TEXT_5 (GUI_ID_USER + 0x0D)
#define ID_TEXT_6 (GUI_ID_USER + 0x0E)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0F)
#define ID_BUTTON_4 (GUI_ID_USER + 0x10)
#define ID_SPINBOX_0 (GUI_ID_USER + 0x11)
#define ID_BUTTON_5 (GUI_ID_USER + 0x12)
#define ID_TEXT_7 (GUI_ID_USER + 0x1B)
#define ID_TEXT_8 (GUI_ID_USER + 0x1A)

/* Sent value defines */
#define PROJECTOR_UP		1
#define PROJECTOR_STOP		2
#define PROJECTOR_DOWN		3
#define AC_STATE_CHANGE		1
#define AC_STATE_NOCHANGE	0
#define AC_SWING_ON			1
#define AC_SWING_OFF		0
#define AC_MIN_VALUE		16
#define AC_MAX_VALUE		30
#define AC_BLADE_0			0
#define AC_BLADE_1			1
#define AC_BLADE_2			2
#define AC_BLADE_3			3
#define AC_BLADE_4			4
#define AC_BLADE_5			5


#define AC_IS_OFF			0
#define AC_IS_ON			1

osThreadDef(PROJECTOR, projector_client_thread, osPriorityNormal, 0, configMINIMAL_STACK_SIZE * 2);

WM_HWIN main_window;
WM_HWIN hItem;
WM_HWIN swing_button;
WM_HWIN AC_control;
WM_HWIN AC_on_off;
WM_HWIN AC_L_control;

uint8_t ac_state = 0;
uint8_t ac_swing_state = 0;
uint8_t ac_lever_state = 0;
int ac_temperature;
uint8_t ac_controls[5] = {6, 1, 0, 3, 0};	//initialization for testing

uint8_t proj_control;

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 1, 0x0, 0 },
  { BUTTON_CreateIndirect, "UP", ID_BUTTON_0, 410, 27, 50, 50, 0, 0x0, 0 },
};

/*********************************************************************
*
*       _cbDialog
*/
void _cbDialog(WM_MESSAGE * pMsg)
{
	WM_HWIN hItem;
	int     NCode;
	int     Id;
	switch (pMsg->MsgId) {
	case WM_INIT_DIALOG:
		hItem = pMsg->hWin;
		break;
	case WM_NOTIFY_PARENT:
		Id    = WM_GetId(pMsg->hWinSrc);
		NCode = pMsg->Data.v;
		switch(Id) {
		case ID_BUTTON_0:
			switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				proj_control = PROJECTOR_UP;
				osThreadCreate (osThread(PROJECTOR), proj_control);
				break;
			case WM_NOTIFICATION_RELEASED:
				break;
			}
			break;
		}
	}
}

WM_HWIN CreateWindow(void)
{
  main_window = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);		//
  return main_window;
}

void MainTask(void)
{
   CreateWindow() ;
}
